# Dependencies
markdown: kramdown

# Setup
title: 'General Physics'
tagline: '@ Berea College'
url: https://github.com/veillette/physics-book

author:
  name: 'Openstax'
  url: https://github.com/openstax

paginate: 5

# Custom vars
version: 11.1
