
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Physics'

url:              https://github.com/veillette/physics-book

tagline:          'from http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@10.1 (CC-BY)'

origin:           http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@10.1

author:
  name:           'Derived from Openstax'
  url:            https://github.com/openstax

# Custom vars
version:          10.1

bookviewer:       https://philschatz.com/book-viewer
