# Dependencies
markdown: kramdown

# Permalinks
#permalink:        pretty

# Setup
title: 'Physics'
tagline: 'from http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@11.1 (CC-BY)'
url: https://github.com/veillette/physics-book
origin: http://cnx.org/contents/031da8d3-b525-429c-80cf-6c8ed997733a@11.1

baseurl: /physics-book

author:
  name: 'Openstax'
  url: https://github.com/openstax

#paginate:         5

# Custom vars
version: 11.1

bookviewer: https://philschatz.com/book-viewer
relative_assets: https://veillette.github.io/physics-book/assets
relativeJs: https://veillette.github.io/physics-book/assets/js/book-viewer.js